name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - headlessChrome
          - edge
          - safari

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12

      - name: npm ci
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm ci

      - run: npm run lint

      - name: npm test
        uses: ianwalter/puppeteer-container@v4.0.0
        env:
          SELENIUM_SERVER: hub.browserstack.com
          SELENIUM_USER: ${{ secrets.BSTACK_USERNAME }}
          SELENIUM_KEY: ${{ secrets.BSTACK_ACCESS_KEY }}
          BROWSER: ${{ matrix.browser }}
        with:
          args: npm test
