name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - chrome
          - edge
          - safari
    env:
      SELENIUM_SERVER: hub.browserstack.com
      SELENIUM_USER: ${{ secrets.BSTACK_USERNAME }}
      SELENIUM_KEY: ${{ secrets.BSTACK_ACCESS_KEY }}
      BROWSER: ${{ matrix.browser }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12

      - name: npm ci
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm ci

      - run: npm run lint

      - if: matrix.browser == 'puppeteer'
        name: npm test
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm test

      - if: matrix.browser != 'puppeteer'
        run: npm test
