name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - name: npm ci
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm ci
      - run: npm run lint
      - name: npm test
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm test
