name: Runner

on:
  workflow_dispatch:
    inputs:
      feature-files:
        description: Feature files to run (a file name or a glob pattern)
        required: true
        default: 'features/**/*.feature'
      cucumber-args:
        description: Additional cucumber-js CLI arguments
        default: '--publish'

jobs:
  runner:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ github.event.inputs.base-url }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - name: npm ci
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm ci
      - name: cucumber-js
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: "npx cucumber-js -r src/index.js ${{ github.event.inputs.feature-files }} ${{ github.event.inputs.cucumber-args }}"
