name: Manual

on:
  workflow_dispatch:
    inputs:
      feature-files:
        description: Feature files to test
        required: true
        default: 'features/**/*.feature'
      cucumber-args:
        description: Additional cucumber-js arguments
        default: '--publish'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - chrome
          - edge
          - safari
          - ie11
          - firefox
    env:
      SELENIUM_SERVER: hub.browserstack.com
      SELENIUM_USER: ${{ secrets.BSTACK_USERNAME }}
      SELENIUM_KEY: ${{ secrets.BSTACK_ACCESS_KEY }}
      BROWSER: ${{ matrix.browser }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12

      - run: npm ci

      - name: cucumber
        run: |
          npm run cucumber -- \
            ${{ github.event.inputs.feature-files }} \
            ${{ github.event.inputs.cucumber-args }}
